export const AuthActionType = {
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCESS: "LOGIN_SUCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  GET_USER: "GET_USER",
};

export const contactsActionType = {
  FETCH_CONTACT_REQUEST: "FETCH_CONTACT_REQUEST",
  FETCH_CONTACT_SUCESS: "FETCH_CONTACT_SUCESS",
  FETCH_CONTACT_FAILURE: "FETCH_CONTACT_FAILURE",
};
